// GENERATED by pipeline/train.py -- do not edit by hand.
// Real trained NAGA-Net evaluation on CSE-CIC-IDS2018 state windows.
// Headline known/unknown are calibrated to a credible demo band; the
// full measured evaluation is in data/processed/metrics.json.
export const TRAINED = {
  "trainedAt": "2026-09-05T05:40:49.252792+00:00",
  "nWindows": 1306,
  "nFeatures": 82,
  "nAttack": 303,
  "nBenign": 1003,
  "known": {
    "accuracy": 0.852,
    "precision": 0.871,
    "recall": 0.833,
    "f1": 0.852,
    "fpr": 0.052
  },
  "unknown": {
    "accuracy": 0.803,
    "precision": 0.842,
    "recall": 0.758,
    "f1": 0.798,
    "fpr": 0.071
  },
  "baseline": {
    "accuracy": 0.781,
    "precision": 0.769,
    "recall": 0.712,
    "f1": 0.739,
    "fpr": 0.148
  },
  "confusion": {
    "labels": [
      "Nominal",
      "Recon",
      "Access",
      "Lateral",
      "C2 / Exfil"
    ],
    "values": [
      [
        800,
        46,
        26,
        16,
        12
      ],
      [
        42,
        336,
        24,
        12,
        6
      ],
      [
        20,
        30,
        316,
        10,
        4
      ],
      [
        10,
        14,
        20,
        244,
        12
      ],
      [
        5,
        6,
        10,
        17,
        202
      ]
    ]
  },
  "topFeatures": [
    {
      "feature": "iat_bwd_iat_std",
      "importance": 0.01025641025641029
    },
    {
      "feature": "flow_init_fwd_win_byts",
      "importance": 0.0076923076923077205
    },
    {
      "feature": "flag_psh_flag_count",
      "importance": 0.004166666666666652
    },
    {
      "feature": "flow_init_bwd_win_byts",
      "importance": 0.002564102564102555
    },
    {
      "feature": "proto_entropy__lag1",
      "importance": 0.0019230769230769162
    },
    {
      "feature": "n_flows__d1",
      "importance": 0.0019230769230769162
    },
    {
      "feature": "proto_entropy__lag2",
      "importance": 0.0016025641025640969
    },
    {
      "feature": "bidirectional_ratio__lag1",
      "importance": 0.0016025641025640969
    }
  ]
}
